apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-frontend-pod
  template:
    metadata:
      labels:
        app: inventory-frontend-pod
    spec:
      containers:
        - name: inventory-frontend-container
          image: nexus.mynisum.com:2376/ascend-kafka/inventory-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
      imagePullSecrets:
        - name: registry-creds

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventory-frontend-pod
